// <auto-generated />
using System;
using Filmes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Filmes.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241121035738_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Filmes.Models.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoLancamento")
                        .HasColumnType("int");

                    b.Property<decimal>("Bilheteria")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Classificacao")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duracao")
                        .HasColumnType("time");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TB_FILMES", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoLancamento = 2014,
                            Bilheteria = 774000000m,
                            Classificacao = 10,
                            Duracao = new TimeSpan(0, 2, 49, 0, 0),
                            Genero = 3,
                            Nome = "Interestelar"
                        },
                        new
                        {
                            Id = 2,
                            AnoLancamento = 2013,
                            Bilheteria = 426074373m,
                            Classificacao = 16,
                            Duracao = new TimeSpan(0, 2, 45, 0, 0),
                            Genero = 0,
                            Nome = "Django Livre"
                        },
                        new
                        {
                            Id = 3,
                            AnoLancamento = 2016,
                            Bilheteria = 340600000m,
                            Classificacao = 0,
                            Duracao = new TimeSpan(0, 2, 8, 0, 0),
                            Genero = 0,
                            Nome = "La La Land"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
